<a href="https://colab.research.google.com/github/Pratikshapawar-star/python-internship-practice-code/blob/main/airlines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data_frame = pd.read_csv("airlines.csv")
print(data_frame)

     Airport.Code                                       Airport.Name  \
0             ATL  Atlanta, GA: Hartsfield-Jackson Atlanta Intern...
1             BOS                    Boston, MA: Logan International
2             BWI  Baltimore, MD: Baltimore/Washington Internatio...
3             CLT     Charlotte, NC: Charlotte Douglas International
4             DCA  Washington, DC: Ronald Reagan Washington National
...           ...                                                ...
4403          SAN             San Diego, CA: San Diego International
4404          SEA          Seattle, WA: Seattle/Tacoma International
4405          SFO     San Francisco, CA: San Francisco International
4406          SLC   Salt Lake City, UT: Salt Lake City International
4407          TPA                     Tampa, FL: Tampa International

     Time.Label  Time.Month Time.Month Name  Time.Year  \
0       2003/06           6            June       2003
1       2003/06           6            June       2003
2       2003/06           6            June       2003
3       2003/06           6            June       2003
4       2003/06           6            June       2003
...         ...         ...             ...        ...
4403    2016/01           1         January       2016
4404    2016/01           1         January       2016
4405    2016/01           1         January       2016
4406    2016/01           1         January       2016
4407    2016/01           1         January       2016

      Statistics.# of Delays.Carrier  Statistics.# of Delays.Late Aircraft  \
0                               1009                                  1275
1                                374                                   495
2                                296                                   477
3                                300                                   472
4                                283                                   268
...                              ...                                   ...
4403                             280                                   397
4404                             357                                   513
4405                             560                                   947
4406                             338                                   540
4407                             410                                   342

      Statistics.# of Delays.National Aviation System  \
0                                                3217
1                                                 685
2                                                 389
3                                                 735
4                                                 487
...                                               ...
4403                                              171
4404                                              351
4405                                             2194
4406                                              253
4407                                              312

      Statistics.# of Delays.Security  ...  Statistics.Flights.Delayed  \
0                                  17  ...                        5843
1                                   3  ...                        1623
2                                   8  ...                        1245
3                                   2  ...                        1562
4                                   4  ...                        1100
...                               ...  ...                         ...
4403                                2  ...                         871
4404                                2  ...                        1274
4405                                2  ...                        3825
4406                                3  ...                        1175
4407                                2  ...                        1095

     Statistics.Flights.Diverted  Statistics.Flights.On Time  \
0                             27                       23974
1                              3                        7875
2                             15                        6998
3                             14                        7021
4                             18                        5321
...                          ...                         ...
4403                          18                        5030
4404                          31                        8330
4405                          20                        8912
4406                          14                        7426
4407                           7                        4748

      Statistics.Flights.Total  Statistics.Minutes Delayed.Carrier  \
0                        30060                               61606
1                         9639                               20319
2                         8287                               13635
3                         8670                               14763
4                         6513                               13775
...                        ...                                 ...
4403                      6016                               15482
4404                      9739                               25461
4405                     13206                               43641
4406                      8699                               32066
4407                      5996                               22557

      Statistics.Minutes Delayed.Late Aircraft  \
0                                        68335
1                                        28189
2                                        26810
3                                        23379
4                                        13712
...                                        ...
4403                                     23023
4404                                     32693
4405                                     72557
4406                                     33682
4407                                     21164

      Statistics.Minutes Delayed.National Aviation System  \
0                                                118831
1                                                 24400
2                                                 17556
3                                                 23804
4                                                 20999
...                                                 ...
4403                                               6021
4404                                              11466
4405                                             153416
4406                                               8057
4407                                              11423

      Statistics.Minutes Delayed.Security  Statistics.Minutes Delayed.Total  \
0                                     518                            268764
1                                      99                             77167
2                                     278                             64480
3                                     127                             65865
4                                     120                             52747
...                                   ...                               ...
4403                                   79                             46206
4404                                   73                             74017
4405                                   66                            278610
4406                                   57                             76978
4407                                   37                             57774

      Statistics.Minutes Delayed.Weather
0                                  19474
1                                   4160
2                                   6201
3                                   3792
4                                   4141
...                                  ...
4403                                1601
4404                                4324
4405                                8930
4406                                3116
4407                                2593

[4408 rows x 24 columns]

In [ ]:
df.pd.read_csv("airlines.csv",usecols=["Airport.Code","Airport.Name"])
print(data_frame)

NameError: name 'df' is not defined

In [ ]:
print(data_frame.shape)

(4408, 24)

In [ ]:
print(data_frame.size)

105792

In [ ]:
print(len(data_frame))

4408

In [ ]:
print(data_frame.index)

RangeIndex(start=0, stop=4408, step=1)

In [ ]:
print(data_frame.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4408 entries, 0 to 4407
Data columns (total 24 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Airport.Code                                         4408 non-null   object
 1   Airport.Name                                         4408 non-null   object
 2   Time.Label                                           4408 non-null   object
 3   Time.Month                                           4408 non-null   int64
 4   Time.Month Name                                      4408 non-null   object
 5   Time.Year                                            4408 non-null   int64
 6   Statistics.# of Delays.Carrier                       4408 non-null   int64
 7   Statistics.# of Delays.Late Aircraft                 4408 non-null   int64
 8   Statistics.# of Delays.National Aviation System      4408 non-null   int64
 9   Statistics.# of Delays.Security                      4408 non-null   int64
 10  Statistics.# of Delays.Weather                       4408 non-null   int64
 11  Statistics.Carriers.Names                            4408 non-null   object
 12  Statistics.Carriers.Total                            4408 non-null   int64
 13  Statistics.Flights.Cancelled                         4408 non-null   int64
 14  Statistics.Flights.Delayed                           4408 non-null   int64
 15  Statistics.Flights.Diverted                          4408 non-null   int64
 16  Statistics.Flights.On Time                           4408 non-null   int64
 17  Statistics.Flights.Total                             4408 non-null   int64
 18  Statistics.Minutes Delayed.Carrier                   4408 non-null   int64
 19  Statistics.Minutes Delayed.Late Aircraft             4408 non-null   int64
 20  Statistics.Minutes Delayed.National Aviation System  4408 non-null   int64
 21  Statistics.Minutes Delayed.Security                  4408 non-null   int64
 22  Statistics.Minutes Delayed.Total                     4408 non-null   int64
 23  Statistics.Minutes Delayed.Weather                   4408 non-null   int64
dtypes: int64(19), object(5)
memory usage: 826.6+ KB
None

In [ ]:
print(data_frame.describe())

        Time.Month    Time.Year  Statistics.# of Delays.Carrier  \
count  4408.000000  4408.000000                     4408.000000
mean      6.578947  2009.243421                      574.632486
std       3.457890     3.667475                      329.616475
min       1.000000  2003.000000                      112.000000
25%       4.000000  2006.000000                      358.000000
50%       7.000000  2009.000000                      476.000000
75%      10.000000  2012.000000                      692.000000
max      12.000000  2016.000000                     3087.000000

       Statistics.# of Delays.Late Aircraft  \
count                           4408.000000
mean                             789.078947
std                              561.798420
min                               86.000000
25%                              425.000000
50%                              618.500000
75%                              959.000000
max                             4483.000000

       Statistics.# of Delays.National Aviation System  \
count                                      4408.000000
mean                                        954.580309
std                                         921.907801
min                                          61.000000
25%                                         399.000000
50%                                         667.500000
75%                                        1166.000000
max                                        9066.000000

       Statistics.# of Delays.Security  Statistics.# of Delays.Weather  \
count                      4408.000000                     4408.000000
mean                          5.575544                       78.216878
std                           6.007046                       75.181726
min                          -1.000000                        1.000000
25%                           2.000000                       33.000000
50%                           4.000000                       58.000000
75%                           7.000000                       98.000000
max                          94.000000                      812.000000

       Statistics.Carriers.Total  Statistics.Flights.Cancelled  \
count                4408.000000                   4408.000000
mean                   12.253403                    213.558076
std                     2.289861                    288.873477
min                     3.000000                      3.000000
25%                    11.000000                     58.000000
50%                    12.000000                    123.000000
75%                    14.000000                    250.000000
max                    18.000000                   3680.000000

       Statistics.Flights.Delayed  Statistics.Flights.Diverted  \
count                 4408.000000                  4408.000000
mean                  2402.000454                    27.880898
std                   1710.947613                    36.356399
min                    283.000000                     0.000000
25%                   1298.750000                     8.000000
50%                   1899.000000                    15.000000
75%                   2950.000000                    32.000000
max                  13699.000000                   442.000000

       Statistics.Flights.On Time  Statistics.Flights.Total  \
count                 4408.000000               4408.000000
mean                  9254.420826              11897.860254
std                   5337.214211               6861.691876
min                   2003.000000               2533.000000
25%                   5708.750000               7400.000000
50%                   7477.000000               9739.500000
75%                  10991.500000              13842.500000
max                  31468.000000              38241.000000

       Statistics.Minutes Delayed.Carrier  \
count                         4408.000000
mean                         35021.369782
std                          24327.721037
min                           6016.000000
25%                          19530.750000
50%                          27782.000000
75%                          41606.000000
max                         220796.000000

       Statistics.Minutes Delayed.Late Aircraft  \
count                               4408.000000
mean                               49410.274955
std                                38750.017050
min                                 5121.000000
25%                                25084.250000
50%                                37483.000000
75%                                59951.250000
max                               345456.000000

       Statistics.Minutes Delayed.National Aviation System  \
count                                        4408.000000
mean                                        45077.107985
std                                         57636.745683
min                                          2183.000000
25%                                         14389.000000
50%                                         25762.000000
75%                                         50362.000000
max                                        602479.000000

       Statistics.Minutes Delayed.Security  Statistics.Minutes Delayed.Total  \
count                          4408.000000                       4408.000000
mean                            211.769737                     135997.535163
std                             257.174789                     113972.276370
min                               0.000000                      14752.000000
25%                              65.000000                      65444.750000
50%                             141.000000                     100711.000000
75%                             274.000000                     164294.750000
max                            4949.000000                     989367.000000

       Statistics.Minutes Delayed.Weather
count                         4408.000000
mean                          6276.982759
std                           6477.417169
min                             46.000000
25%                           2310.750000
50%                           4298.500000
75%                           7846.000000
max                          76770.000000

In [ ]:
data_frame.describe(include="all")

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
count,4408,4408,4408,4408.000000,4408,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000,...,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000,4408.000000
unique,29,29,152,NaN,12,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2003/06,NaN,June,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,152,152,29,NaN,377,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,6.578947,NaN,2009.243421,574.632486,789.078947,954.580309,5.575544,...,2402.000454,27.880898,9254.420826,11897.860254,35021.369782,49410.274955,45077.107985,211.769737,135997.535163,6276.982759
std,NaN,NaN,NaN,3.457890,NaN,3.667475,329.616475,561.798420,921.907801,6.007046,...,1710.947613,36.356399,5337.214211,6861.691876,24327.721037,38750.017050,57636.745683,257.174789,113972.276370,6477.417169
min,NaN,NaN,NaN,1.000000,NaN,2003.000000,112.000000,86.000000,61.000000,-1.000000,...,283.000000,0.000000,2003.000000,2533.000000,6016.000000,5121.000000,2183.000000,0.000000,14752.000000,46.000000
25%,NaN,NaN,NaN,4.000000,NaN,2006.000000,358.000000,425.000000,399.000000,2.000000,...,1298.750000,8.000000,5708.750000,7400.000000,19530.750000,25084.250000,14389.000000,65.000000,65444.750000,2310.750000
50%,NaN,NaN,NaN,7.000000,NaN,2009.000000,476.000000,618.500000,667.500000,4.000000,...,1899.000000,15.000000,7477.000000,9739.500000,27782.000000,37483.000000,25762.000000,141.000000,100711.000000,4298.500000
75%,NaN,NaN,NaN,10.000000,NaN,2012.000000,692.000000,959.000000,1166.000000,7.000000,...,2950.000000,32.000000,10991.500000,13842.500000,41606.000000,59951.250000,50362.000000,274.000000,164294.750000,7846.000000
max,NaN,NaN,NaN,12.000000,NaN,2016.000000,3087.000000,4483.000000,9066.000000,94.000000,...,13699.000000,442.000000,31468.000000,38241.000000,220796.000000,345456.000000,602479.000000,4949.000000,989367.000000,76770.000000

In [ ]:
print(data_frame.dtypes)

Airport.Code                                           object
Airport.Name                                           object
Time.Label                                             object
Time.Month                                              int64
Time.Month Name                                        object
Time.Year                                               int64
Statistics.# of Delays.Carrier                          int64
Statistics.# of Delays.Late Aircraft                    int64
Statistics.# of Delays.National Aviation System         int64
Statistics.# of Delays.Security                         int64
Statistics.# of Delays.Weather                          int64
Statistics.Carriers.Names                              object
Statistics.Carriers.Total                               int64
Statistics.Flights.Cancelled                            int64
Statistics.Flights.Delayed                              int64
Statistics.Flights.Diverted                             int64
Statistics.Flights.On Time                              int64
Statistics.Flights.Total                                int64
Statistics.Minutes Delayed.Carrier                      int64
Statistics.Minutes Delayed.Late Aircraft                int64
Statistics.Minutes Delayed.National Aviation System     int64
Statistics.Minutes Delayed.Security                     int64
Statistics.Minutes Delayed.Total                        int64
Statistics.Minutes Delayed.Weather                      int64
dtype: object

In [ ]:
#change the into46 in float64
data_frame["Time.Month"]= data_frame["Time.Month"].astype("float")

In [ ]:
data_frame["Time.Month"].dtypes

dtype('float64')

In [ ]:
data_frame.rename(columns = {"Airport.Code":"Airport_code"},inplace=True)

In [ ]:
data_frame.columns

Index(['Airport_code', 'Airport.Name', 'Time.Label', 'Time.Month',
       'Time.Month Name', 'Time.Year', 'Statistics.# of Delays.Carrier',
       'Statistics.# of Delays.Late Aircraft',
       'Statistics.# of Delays.National Aviation System',
       'Statistics.# of Delays.Security', 'Statistics.# of Delays.Weather',
       'Statistics.Carriers.Names', 'Statistics.Carriers.Total',
       'Statistics.Flights.Cancelled', 'Statistics.Flights.Delayed',
       'Statistics.Flights.Diverted', 'Statistics.Flights.On Time',
       'Statistics.Flights.Total', 'Statistics.Minutes Delayed.Carrier',
       'Statistics.Minutes Delayed.Late Aircraft',
       'Statistics.Minutes Delayed.National Aviation System',
       'Statistics.Minutes Delayed.Security',
       'Statistics.Minutes Delayed.Total',
       'Statistics.Minutes Delayed.Weather'],
      dtype='object')

In [ ]:
data_frame["Airport.Name"].unique()

array(['Atlanta, GA: Hartsfield-Jackson Atlanta International',
       'Boston, MA: Logan International',
       'Baltimore, MD: Baltimore/Washington International Thurgood Marshall',
       'Charlotte, NC: Charlotte Douglas International',
       'Washington, DC: Ronald Reagan Washington National',
       'Denver, CO: Denver International',
       'Dallas/Fort Worth, TX: Dallas/Fort Worth International',
       'Detroit, MI: Detroit Metro Wayne County',
       'Newark, NJ: Newark Liberty International',
       'Fort Lauderdale, FL: Fort Lauderdale-Hollywood International',
       'Washington, DC: Washington Dulles International',
       'Houston, TX: George Bush Intercontinental/Houston',
       'New York, NY: John F. Kennedy International',
       'Las Vegas, NV: McCarran International',
       'Los Angeles, CA: Los Angeles International',
       'New York, NY: LaGuardia', 'Orlando, FL: Orlando International',
       'Chicago, IL: Chicago Midway International',
       'Miami, FL: Miami International',
       'Minneapolis, MN: Minneapolis-St Paul International',
       "Chicago, IL: Chicago O'Hare International",
       'Portland, OR: Portland International',
       'Philadelphia, PA: Philadelphia International',
       'Phoenix, AZ: Phoenix Sky Harbor International',
       'San Diego, CA: San Diego International',
       'Seattle, WA: Seattle/Tacoma International',
       'San Francisco, CA: San Francisco International',
       'Salt Lake City, UT: Salt Lake City International',
       'Tampa, FL: Tampa International'], dtype=object)

In [ ]:
data_frame["Airport.Name"].nunique()

29

In [ ]:
data_frame["Airport.Name"].value_counts()

Airport.Name
Atlanta, GA: Hartsfield-Jackson Atlanta International                  152
Boston, MA: Logan International                                        152
Baltimore, MD: Baltimore/Washington International Thurgood Marshall    152
Charlotte, NC: Charlotte Douglas International                         152
Washington, DC: Ronald Reagan Washington National                      152
Denver, CO: Denver International                                       152
Dallas/Fort Worth, TX: Dallas/Fort Worth International                 152
Detroit, MI: Detroit Metro Wayne County                                152
Newark, NJ: Newark Liberty International                               152
Fort Lauderdale, FL: Fort Lauderdale-Hollywood International           152
Washington, DC: Washington Dulles International                        152
Houston, TX: George Bush Intercontinental/Houston                      152
New York, NY: John F. Kennedy International                            152
Las Vegas, NV: McCarran International                                  152
Los Angeles, CA: Los Angeles International                             152
New York, NY: LaGuardia                                                152
Orlando, FL: Orlando International                                     152
Chicago, IL: Chicago Midway International                              152
Miami, FL: Miami International                                         152
Minneapolis, MN: Minneapolis-St Paul International                     152
Chicago, IL: Chicago O'Hare International                              152
Portland, OR: Portland International                                   152
Philadelphia, PA: Philadelphia International                           152
Phoenix, AZ: Phoenix Sky Harbor International                          152
San Diego, CA: San Diego International                                 152
Seattle, WA: Seattle/Tacoma International                              152
San Francisco, CA: San Francisco International                         152
Salt Lake City, UT: Salt Lake City International                       152
Tampa, FL: Tampa International                                         152
Name: count, dtype: int64

In [ ]:
data = pd.DataFrame({"Name":["Alice", "Bob", "Charlie","David"],
                     "Age": [25,50,35,48],
                     "Salary": [10000,96000,54000,52000]})
print(data)
sorted_data = data.sort_index(axis=0, ascending=False)
print("\n",sorted_data)

      Name  Age  Salary
0    Alice   25   10000
1      Bob   50   96000
2  Charlie   35   54000
3    David   48   52000

       Name  Age  Salary
3    David   48   52000
2  Charlie   35   54000
1      Bob   50   96000
0    Alice   25   10000

In [ ]:
sorted_data = data.sort_index(axis=1, ascending=True)
print(sorted_data)

   Age     Name  Salary
0   25    Alice   10000
1   50      Bob   96000
2   35  Charlie   54000
3   48    David   52000

In [ ]:
sorted_data= data.sort_values(by="Age", ascending=True )
print(sorted_data)

      Name  Age  Salary
0    Alice   25   10000
2  Charlie   35   54000
3    David   48   52000
1      Bob   50   96000

In [ ]:
data=pd.DataFrame({"Name":["Alice", "Bob", "Charlie","David"],
                     "Age": [25,50,35,48],
                     "Salary": [10000,96000,54000,52000]})
print (data)
sorted_data= data.sort_values(by=["Name","Salary"], ascending=[True, False])
print("\n After Sorting","\n", sorted_data)

      Name  Age  Salary
0    Alice   25   10000
1      Bob   50   96000
2  Charlie   35   54000
3    David   48   52000

 After Sorting
       Name  Age  Salary
0    Alice   25   10000
1      Bob   50   96000
2  Charlie   35   54000
3    David   48   52000

Exercise 5

In [ ]:
import pandas as pd
df = pd.read_csv("nba.csv")
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df["Team"].nunique("College")

30

In [ ]:
df["College"].nunique("College")

118

In [ ]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(104)

In [ ]:
df.loc[0:4,:]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0