<a href="https://colab.research.google.com/github/Pratikshapawar-star/python-internship-practice-code/blob/main/Day9_waste_manag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
import joblib
from sklearn.svm import SVC

In [ ]:
df=pd.read_csv('/content/waste management.csv')

In [ ]:
df.head()

   waste_type  material_composition  ...  toxicity_level  management_strategy
0           3              0.198716  ...       81.011339                    0
1           1              0.005522  ...       86.707232                    0
2           3              0.815461  ...       91.324055                    0
3           3              0.706857  ...       51.134240                    0
4           1              0.729007  ...       50.151629                    0

[5 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   waste_type            100 non-null    int64
 1   material_composition  100 non-null    float64
 2   recycling_potential   100 non-null    float64
 3   toxicity_level        100 non-null    float64
 4   management_strategy   100 non-null    int64
dtypes: float64(3), int64(2)
memory usage: 4.0 KB

In [ ]:
df.isnull().sum()

waste_type              0
material_composition    0
recycling_potential     0
toxicity_level          0
management_strategy     0
dtype: int64

In [ ]:
x=df[['material_composition','recycling_potential','toxicity_level','waste_type']]
y=df['management_strategy']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from numpy.random.mtrand import gamma
model=SVC(kernel='rbf', C=1.0,gamma='scale')
model.fit(x_train,y_train)

SVC()

In [ ]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [ ]:
joblib.dump(scaler, 'scaler.joblib')
print("Scaler saved as 'scaler.joblib'.")

Scaler saved as 'scaler.joblib'.

In [ ]:
dt_model1= DecisionTreeClassifier()
dt_model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dt1=dt_model1.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred_dt1)

0.95

In [ ]:
dt_model2=LogisticRegression(random_state=42)
dt_model2.fit(x_train,y_train)

LogisticRegression(random_state=42)

In [ ]:
y_pred_dt2=dt_model2.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred_dt2)

0.9

In [ ]:
rf_model3=RandomForestClassifier(n_estimators=100,random_state=42)
rf_model3.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred_rf3=rf_model3.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred_rf3)

0.95

In [ ]:
import gradio as gr
import joblib
import pandas as pd

In [ ]:
joblib.dump(scaler, 'waste_management_model.joblib')
print("Scaler saved as ''waste_management_model.joblib'")

Scaler saved as ''waste_management_model.joblib'

In [ ]:
model = joblib.load('waste_management_model.joblib')

In [ ]:
def predict_management_strategy(waste_type, material_composition, recycling_potential, toxicity_level):
  input_data = pd.DataFrame({
      'waste_type': [waste_type],
      'material_composition': [material_composition],
      'recycling_potential': [recycling_potential],
      'toxicity_level': [toxicity_level]
  })

  prediction = model.predict(input_data)[0]

  if prediction ==0:
    return 'Non-recyclable'
  else:
    return 'Recyclable'

In [ ]:
waste_type_input= gr.Slider(minimum=1,maximum=3,step=1,label='Waste Type(1-3)')
matrial_composition_input=gr.Slider(minimum=0.0, maximum=1.0,step=0.01,label='Material Composition(0-1)')
recycling_potential_input=gr.Slider(minimum=0.0, maximum=1.0,step=0.01,label='Recycling Potential(0-1)')
toxicity_level_input=gr.Slider(minimum=0.0, maximum=100.0,step=0.1,label='Toxicity Level(0-100)')

interface = gr.Interface(
    fn=predict_management_strategy,
    inputs=[
        waste_type_input,
        matrial_composition_input,
        recycling_potential_input,
        toxicity_level_input
    ],
    outputs='text',
    title='Waste Management Strategy Predictor',
    description='Enter the waste characteristics to predict the management strategy (Non-Recyclable or Recyclable).'
)
interface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://beae5dd23df8b329ef.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)