<a href="https://colab.research.google.com/github/Pratikshapawar-star/python-internship-practice-code/blob/main/Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data={
    "Days":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
    "Index":[1,2,3,4,5,6,7,]

}

In [ ]:
df=pd.DataFrame(data)
print(df)

        Days  Index
0     Monday      1
1    Tuesday      2
2  Wednesday      3
3   Thursday      4
4     Friday      5
5   Saturday      6
6     Sunday      7

In [ ]:
print(df.loc[4])

Days     Friday
Index         5
Name: 4, dtype: object

In [ ]:
data_frame={
    "Name":["Alice","Bob","Charlie"],
    "Age":[25,30,28],
    "City":["New York","Los Angeles", "Chicago"]
}

In [ ]:
df=pd.DataFrame(data_frame)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   28      Chicago

In [ ]:
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [ ]:
sort_df = df.sort_values(by="Age")
print(sort_df)

      Name  Age         City
0    Alice   25     New York
2  Charlie   28      Chicago
1      Bob   30  Los Angeles

In [ ]:
print(df.shape)

(3, 3)

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "Date": pd.date_range(start="2021-10-01", periods=10),
    "Measurement":[16,13,14,12,np.nan,np.nan,np.nan,8,7,5]
})
print(df)

        Date  Measurement
0 2021-10-01         16.0
1 2021-10-02         13.0
2 2021-10-03         14.0
3 2021-10-04         12.0
4 2021-10-05          NaN
5 2021-10-06          NaN
6 2021-10-07          NaN
7 2021-10-08          8.0
8 2021-10-09          7.0
9 2021-10-10          5.0

In [ ]:
def fill_missing_values():
  try:
    df.fillna(method="ffill", limit=2,inplace=True)
    df.fillna(value=df["Measurement"].mean(), inplace=True)
    return list(df["Measurement"])

    except:
      pass

SyntaxError: invalid syntax (ipython-input-509933621.py, line 7)

In [ ]:
df = pd.read_csv("music.csv")

df

              artist  country  plays  genre  fans
0        The Beatles       UK    150   rock    50
1         Pink Floyd       UK  10000   rock  1500
2          Metallica       US    500  metal    50
3           Cairokee    Egypt    200   rock    10
4               ACDC       US    250   rock    20
5          The Doors       US   1000   rock    80
6  Poets of The Fall  Finland    250   rock    10
7           Megadeth       US    300  metal    20
8        Iron Maiden       UK  20000  metal  3500
9       Judas Priest       UK   5000  metal  1000

In [ ]:
df.groupby("country").plays.sum().to_dict()

{'Egypt': 200, 'Finland': 250, 'UK': 35150, 'US': 2050}